package com.gkudva.bart.Util;

/**
 * Created by gkudva on 11/2/15.
 */
public class BartStationList {
    public static String[] stationList = {  "List of all station's in the BART system",
                                            "12th St. Oakland City Center",
                                            "16th St. Mission (SF)",
                                            "19th St. Oakland",
                                            "24th St. Mission (SF)",
                                            "Ashby (Berkeley)",
                                            "Balboa Park (SF)",
                                            "Bay Fair (San Leandro)",
                                            "Castro Valley",
                                            "Civic Center/UN Plaza (SF)",
                                            "Coliseum",
                                            "Colma",
                                            "Concord",
                                            "Daly City",
                                            "Downtown Berkeley",
                                            "Dublin/Pleasanton",
                                            "El Cerrito del Norte",
                                            "El Cerrito Plaza",
                                            "Embarcadero (SF)",
                                            "Fremont",
                                            "Fruitvale (Oakland)",
                                            "Glen Park (SF)",
                                            "Hayward",
                                            "Lafayette",
                                            "Lake Merritt (Oakland)",
                                            "MacArthur (Oakland)",
                                            "Millbrae",
                                            "Montgomery St. (SF)",
                                            "North Berkeley",
                                            "North Concord/Martinez",
                                            "Oakland Int\\'l Airport",
                                            "Orinda",
                                            "Pittsburg/Bay Point",
                                            "Pleasant Hill/Contra Costa Center",
                                            "Powell St. (SF)",
                                            "Richmond",
                                            "Rockridge",
                                            "San Bruno",
                                            "San Francisco Int'l Airport",
                                            "San Leandro",
                                            "South Hayward",
                                            "South San Francisco",
                                            "Union City",
                                            "Walnut Creek",
                                            "West Dublin/Pleasanton",
                                            "West Oakland"};
}
